"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""" VIM Option """""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible        " READ THE DOCS. Plugins often depend on this 

" Load any vim files located in '~/.vim/custom/'
" This includes our Plugins, Remaps, and whatever
let customdir='~/.vim/custom/'
function LoadCustom()
    let customfiles=split(globpath(expand(g:customdir),'*.vim'), '\n')
    for cf in customfiles
        if filereadable(expand(cf))
            execute 'source ' . cf
        else
            echom "Wasn't able to read " .. cf
        endif
    endfor
endfunction
" Keep loads above this so they don't mess with these settings
call LoadCustom()

" These settings will override those from above!
syntax on               " Turns on Syntax highlighting 
try
    "colorscheme vividchalk   " Colour Scheme (in ~/.vim/colors)
    colorscheme spaceduck " Colour Scheme (in ~/.vim/colors)
catch
    colorscheme peachpuff   " Backup colour scheme (in /usr/share/vim...)
endtry
" Transparency
"hi Normal guibg=NONE ctermbg=None
set mouse=a             " For people that can't use vim
set path+=**            " Recursive path lookup

set t_Co=256            " Want 256 colors
"set cursorline          " Highlight current line
set lazyredraw          " Faster rendering
set showcmd             " Show command as typing
set wildmenu            " Wildmenu buffer, auto completion

" Add syntax based autocompletion to omnicompletion: <C-x><C-o>
filetype plugin on
set omnifunc=syntaxcomplete#Complete
" If python file loaded load the python3 completion
" Must be built with +python3
autocmd FileType python setlocal omnifunc=python3complete#Complete

" Indenting
set autoindent          " Auto indent
" No indenting on # mark 
set cindent             " Uses C indenting rules (spaces)
set cinkeys-=0#
set indentkeys-=0#
set wrap                " Wraps text
set expandtab           " Spaces and not tabs
set smarttab            " Trys to figure out when to tab
set shiftwidth=4        " Tab width 
set softtabstop=4

set backspace=indent,eol,start  "Backspace works through indents, end of line, etc

set number ruler        "Show line number
set showmode            "Shows mode in bottom left

set scrolloff=5         " Keep at lease 5 lines above and below
set colorcolumn=81      " Vertical white bar at 80 chars
set tw=80               " Line wrapping
" use `gq` to wrap selected text and `gqG` to wrap text till end of file
" all ranges work like normal. `gqip` wraps current paragraph

" Error bells.  All are off
set noerrorbells        " Removes error bells
set novisualbell        " Removes visual bells
set t_vb=               " Sets visual bell

" Searching
set incsearch           " Search command while typing
set hlsearch            " Highlights all misspelled words
set showmatch           " Shows matching brackets
nnoremap <silent> <Space> :silent noh<Bar>echo<CR>
set ignorecase          " Ignore case. Same as /csearchterm
set smartcase           " For searching

" Splitting
set splitright          " Puts new window to right of current (vsplit)
set splitbelow          " Same but below (split)

" Folding:  Press zf to fold highlighted text (zfap for paragraph) 
set foldmethod=indent   " We use python and markdown a lot
autocmd Filetype cpp setlocal foldmethod=marker
set foldcolumn=2        " Shows fold info on left
set foldlevel=4         " Should match shiftwidth

"Ctags
set tags="./.tags,../.tags,~/.tags"

" MARKDOWN
syn match markdownIgnore "\$.*_.*\$" " Doesn't highlight _ while in latex

" Spell checking
" Pressing ,ss will toggle and untoggle spell checking
syntax spell toplevel   " Spell check fixing for tex
map <leader>ss :setlocal spell!<cr>
set spell                     " Turns on Spellcheck
hi clear SpellBad             " Highlights misspelled words
hi SpellBad cterm=underline,bold ctermfg=white "Makes misspelled words highlited, bold, and underline white

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Turn persistent undo on
" means that you can undo even when you close a buffer/VIM
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
try
    set undofile
    set undodir=~/.vim/undodir
catch
endtry
