---
- name: Make ssh-dir if not exist
  ansible.builtin.shell: |
    mkdir -p -m 700 ~/.ssh
    touch ~/.ssh/known_hosts
    chmod 600 ~/.ssh/known_hosts
    touch ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys

- name: Setup authorized key
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ host_uname }}/.ssh/{{ ssh_key }}') }}"
