local wezterm = require 'wezterm'
-- ----------------------------------------------------------- 
-- User defined variables
-- ----------------------------------------------------------- 
local EDITOR = 'vim'
-- Wezterm config hotkeying
local config_key = ','
-- Open dotfiles (dir)
local dotfiles_key = '.'
local dotfiles_dir = wezterm.home_dir .. '/.dotfiles/'
local dotfiles_file = '.'
-- Research Notes hotkeying
local notes_key = 'n'
local research_notes_path = wezterm.home_dir .. '/Documents/Research/ResearchNotes/'
local research_notes_file = 'README.md' -- Opens (autogenerated) README
--                                         press `gf` on file you want
-- ----------------------------------------------------------- 
local module = {}

-- Function make cmd+'key' to open 'args' with EDITOR from 'cwd'
function module.vim_super_open_new_tab(config, key, cwd, args)
    table.insert(config.keys,
        {
            key = key,
            mods = 'SUPER',
            action = wezterm.action.SpawnCommandInNewTab {
                cwd = cwd,
                args = { EDITOR, args },
            },
        }
    )
    return config
end

-- Hotkey to open wezterm config
function module.load_config_in_new_tab(config)
    return module.vim_super_open_new_tab(config, config_key, wezterm.home_dir, wezterm.config_file)
end

-- Hotkey to open research notes
function module.load_notes(config)
    return module.vim_super_open_new_tab(config, notes_key, research_notes_path, research_notes_file)
end

-- Open the dotfiles directory with vim
function module.load_dotfiles(config)
    return module.vim_super_open_new_tab(config, dotfiles_key, dotfiles_dir , dotfiles_file)
end

function module.load_commands(config)
    config = module.load_config_in_new_tab(config)
    config = module.load_notes(config)
    config = module.load_dotfiles(config)
    return config
end

return module
